---
version: "1"
rules:
  - base: master
    upstream: qmk:master
    mergeMethod: hardreset
    mergeUnstable: false
  - base: kruton
    upstream: qmk:master
    mergeMethod: rebase
    conflictReviewers:
      - kruton
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
